export const ADD_TO_CARD = 'ADD_TO_CARD';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const DELETE_PRODUCT_IN_CARD = 'DELETE_PRODUCT_IN_CARD';
export const UPDATE_PRODUCT_IN_CARD = 'UPDATE_PRODUCT_IN_CARD';